### ISSUE TITLE
[Question] using asyc-raft with actix-web

### ISSUE THREAD

**Issue by sivertjoe** [async-raft/async-raft#110]
Im trying to use actix-web as the network layer. 

The current main and toml  looks like this
```rust
#[tokio::main]
async fn main()
{
    let sys = actix_rt::System::new("test");
    let state = Arc::new(Mutex::new(State::new().await));
    spawn_thread(Arc::clone(&state));
    HttpServer::new(move || {
        App::new()
            .data(Arc::clone(&state))
            .service(get_info)
            // Other methods ...
            .service(append_entries)
            .service(install_snapshot)
            .service(vote)
    })
    .bind(format!("0.0.0.0:{}", worm::PORT))
    .unwrap()
    .run().await;
    let _ = sys.run();
}
```
```toml
actix-http = "*"
actix-web = "3.1.0"
actix-rt = "1.1.1"
async-raft = "*"
tokio = { version="1.0", default-features=false, features=["fs", "io-util", "macros", "rt", "rt-multi-thread", "sync", "tim    e"] }
reqwest = { version = "0.11.2", features = ["json"] }
```
(I have omitted some dependencies for simplicity)

Now, `get_info` does another http call, but if I try to call `get_info` (`curl localhost:{port}/get_info`) I get
```bash
thread 'actix-rt:worker:0' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/{user}/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.4.0/src/runtime/blocking/pool.rs:85:33
```

I've tried to google the error and fix it, but I always end up get other errors like this
```bash
thread 'main' panicked at 'System is not running', /home/{user}/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/system.rs:78:21
``` 
or 
```bash
thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime', /home/{user}/.cargo/registry/src/github.com-1ecc6299db9ec823/async-raft-0.6.0/src/core/mod.rs:157:9
```
when trying to configure main differently. I've tried a bunch of things, like wrapping the content of main in a `tokio::runtime::Runtime` and using the `#[actix::main]` attribute, but nothing seems to work.

What is the correct way to use these two libraries together? I'd be glad to provide any more information. 

Any help would be appreciated :pray:!
